# -*- coding: utf-8 -*-
"""Just_For_Fun.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kfvYJyrVdf3jnynYfnUylljFnXh0b-6E

#素数判別
"""

print("入力された数値が素数かどうかを判別します。")
print()

x = int(input("数値を入力してください : "))
y = x // 2 + 1

if x != 1:
  while y > 1:
    if x == 2:
      print(str(x) + "は素数です！")
      break
    elif x % y == 0:
      print("not そすう")
      break
    else:
      y = y - 1
  else:
    print(str(x) + "は素数です！")
else:
  print("not そすう")

print("素数判別機、バージョン2")
print()

num1 = int(input("入力してね : "))
num2 = 1

if num1 == 2:
  print(str(num1) + "は素数です！")
elif num1 % 2 == 0 or num1 == 1:
  print("not そすう")
else:
  while num1 > num2 ** 2:
    num2 = num2 + 2
    if num1 % num2 == 0:
      print("not そすう")
      break
  else:
    print(str(num1) + "は素数です！")

def isprime(num):

  num2 = 1

  if num == 2:
    return True

  elif num % 2 == 0 or num == 1:
    return False

  else:

    while num > num2 ** 2:
      num2 = num2 + 2

      if num % num2 == 0:
        return False
        
        break

    else:
      return True

print("関数isprimeが定義されたよ！！！！")

print("Just another 素数判別機、バージョン2")
print()

num = input("数字をここに → ")

if num.isdigit() == True:
  num = int(num)

  if isprime(num) == True:
    print(str(num) + "は素数です！！！！！！")
    
  else:
    print("primen't")

else:
  print("ばーか")

"""#乱"""

import random

print(random.random())
print(random.randint(1 , 10))
print()

print(max(10 , 20))
print(min(10 , 20))

import random

i = 0
correct = 0

while i < 5:
  i = i + 1
  try:
    x = int(input("attempt(" + str(i) + ") : "))
  except KeyboardInterrupt:
    print("草")
    break
  except ValueError:
    print("あ～ｗ")
    break
  else:
    if 1 <= x <= 10:
      y = random.randint(1 , 10)
      if x == y:
        print("正解!!!!!!!!!!")
        print()
        print()
        correct = correct + 1
      else:
        print("ちがう")
        print("正解は" + str(y))
        print()
    else:
      print("なにやってんの…")
      break
else:
  print("結果発表")
  print("正解数は" + str(correct) + "個")
  if correct == 0:
    print("それが普通") #59.049%
  elif correct == 1:
    print("おめでとう") #32.805%
  elif correct == 2:
    print("すごいね？") #7.29%
  elif correct == 3:
    print("すごくね？？") #0.81%
  elif correct == 4:
    print("？？？？？？？？？？") #0.045%
  elif correct == 5:
    print("何があったの…？") #0.001%

"""#箱"""

box1 = list("python")
print(box1)
print()

box2 = ["P", "y", "t", "h", "o", "n"]
print(box2[3:6])
print("10万円 " + box2[0] + box2[4] + box2[5] + "☆ とくれたぜ")
print()

box3 = list("density")
print(box3)
print(box3[0] + box3[1] + box3[3] + box3[5] + box3[4] + box3[2] + box3[6])
print()

x = 2 ** 6
y = str(x) * 3
print(int(y) - x)

"""#(x^x)+1"""

i = 0
while i < 100:
  i = i + 1
  if (i ** i + 1) % 3 == 0:
    print(i)
else:
  print("done")

"""#完全数"""

import time

h = 0
i = int(input("おかず : "))
j = i // 2 + 1

t1 = time.time()

while 1 < j:
  j = j - 1
  if i % j == 0:
    h = h + j
else:
  if i == h:
    print(str(i) + "は完全数")
  else:
    print("not かんぜんすー")

t2 = time.time()

print()

elapsed_time = t2 - t1
print("処理時間は" + str(round(elapsed_time , 5)) + "秒")

import time

Current = 0 #今調べている数字
Last = int(input("till when : ")) #どこまで調べるか

t1 = time.time() #処理の開始時間

while Last > Current:
  SOD = 0 #約数の総和
  Current = Current + 1
  CheN = Current // 2 + 1 #調べるべき数字
  while 1 < CheN:
    CheN = CheN - 1
    if Current % CheN == 0:
      SOD = SOD + CheN
  else:
    if Current == SOD:
      print(Current)

t2 = time.time() #処理の終了時間

print()

elapsed_time = t2 - t1 #経過時間
print("処理時間は" + str(round(elapsed_time , 2)) + "秒")

"""#マクローリン展開"""

import math as m

print("e^xの近似を求めます。")
x = int(input("何乗の近似を求めますか : "))
last = int(input("近似の回数 : "))
cur = 0 #現在の数
kai = 1 #階乗
ans = 1 #答え
print()

while cur < last:
  cur = cur + 1
  kai = kai * cur
  form = (x ** cur) / kai #式単体
  ans = ans + form
  if cur < 10:
    print(" " + str(cur) + "次近似 : " +str(m.exp(1) - ans))
  elif 10 <= cur < 100:
    print(str(cur) + "次近似 : " +str(m.exp(1) - ans))

"""#数列"""

import time

a1 = int(input("初項 : "))
n = int(input("何項まで : "))
cur = 1 # ただの項数
k = a1 #右上

t1 = time.time()

print("1項目 : " + str(a1))
while cur < n:
  cur = cur + 1
  an = a1 ** (k * 2 + 1)
  k = an
  print(str(cur) + "項目 : " + str(an))

t2 = time.time()

elapsed_time = t2 - t1
print("処理時間は" + str(round(elapsed_time , 5)) + "秒")

"""#BMI"""

weight = float(input("体重[kg] : "))
height = float(input("身長[cm] : "))
bmi = weight / ((height / 100) **2)

print("あなたのBMIは" + str(round(bmi , 3)))

"""#しりとり"""

import random as r

print("最初の文字 : " + str(r.randint(1 , 50)))
print("文字数 : " + str(r.randint(2 , 12)))

"""#すももももももももももも…"""

letter = input("文字を入力してね : ")
target = input("対象の文字をどうぞ : ")
letlist = []

for letters in letter:
  letlist.append(letters)

i = 0
j = 1
objective = ""

while i < len(letlist):
  if letlist[i] == target:
    letlist[i] = target * j
    objective = objective + letlist[i]
    j = j * 2
  else:
    objective = objective + letlist[i]
  i = i + 1

print(objective)

"""# CH Calculator

## Chor'gorloth or Ponyboy
"""

i = 0
while i < 1:
  chorLV = input("Chor'gorloth's level? : ")
  if chorLV.isdigit() == False:
    print("Enter number plz")
    continue
  i = i + 1

i = 0
while i < 1:
  ponyLV = input("Ponyboy's level? : ")
  if ponyLV.isdigit() == False:
    print("Enter number plz")
    continue
  i = i + 1

chorEff = (20 / 19) / (int(chorLV) + 1)
ponyEff = (int(ponyLV) + 1) / (int(ponyLV) ** 2)

print(chorEff , ponyEff)
print(max(chorEff , ponyEff))

"""## Chor's effect"""

lv = input("Level? : ")

if lv.isdigit() == True:
  lv = int(lv)
  effect = 100 * (1 - 0.95 ** lv)

  print(str(round(effect , 2)) + "%")
  
else:
  print("ばーか")

for lvs in range(1 , 151):
  effect = 100 * (1 - 0.95 ** lvs)
  if 1 <= lvs < 10:
    print("Lvl " + str(lvs) + "   : -" + str(round(effect , 4)) + "%")
  elif 11 <= lvs < 100:
    print("Lvl " + str(lvs) + "  : -" + str(round(effect , 4)) + "%")
  elif 101 <= lvs:
    print("Lvl " + str(lvs) + " : -" + str(round(effect , 4)) + "%")

"""## Monster Health"""

import math

lv = input("Level? : ")

if lv.isdigit() == True:
  lv = int(lv)

  if 1 <= lv <= 140:
    health = 10 * (lv - 1 + 1.55 ** (lv - 1))
    if lv % 5 == 0:
      health = 10 * health
    print(str(math.floor(math.log10(math.ceil(health)))) + "digits")

else:
  print("ばーか")

import math

lv = input("Level? : ")

if lv.isdigit() == True:
  lv = int(lv)

  if 1 <= lv <= 140:
    health = math.log10(lv - 1 + 1.55 ** (lv - 1)) + 1

  elif 140 < lv <= 500:
    health = math.log10(139 + 1.55 ** 139 * 1.145 ** (lv - 140)) + 1

  elif 500 < lv <= 200000:
    prd = 0
    for i in range(501 , lv + 1):
      formula = math.log10(1.145 + 0.001 * math.floor((i - 1) / 500))
      prd = prd + formula
    health = (139 * math.log10(1.55)) + (360 * math.log10(1.145)) + prd + 1

  elif 200000 < lv:
    health = (lv - 200001) * math.log10(1.545) + math.log10(1.24) + 25409
    
  if lv % 5 == 0:
    health = health + 1
  print(str(math.floor(health)) + "digits")

else:
  print("ばーか")

"""### Function:CH_MonsterHealth"""

def CH_MonsterHealth(lv):

  import math

  if lv.isdigit() == True:
    lv = int(lv)

    if 1 <= lv <= 140:
      health = math.log10(lv - 1 + 1.55 ** (lv - 1)) + 1

    elif 140 < lv <= 500:
      health = math.log10(139 + 1.55 ** 139 * 1.145 ** (lv - 140)) + 1

    elif 500 < lv <= 200000:
      prd = 0
      for i in range(501 , lv + 1):
        formula = math.log10(1.145 + 0.001 * math.floor((i - 1) / 500))
        prd = prd + formula
      health = (139 * math.log10(1.55)) + (360 * math.log10(1.145)) + prd + 1

    elif 200000 < lv:
      health = (lv - 200001) * math.log10(1.545) + math.log10(1.24) + 25409
        
    if lv % 5 == 0:
      health = health + 1
    return(str(math.floor(health)) + "digits")

  else:
    return("ばーか")

print("関数CH_MonsterHealthが定義されたよ！！！！")

#うごかない！！！！！！ on Colaboratory
"""
import tkinter as tk

root = tk.Tk()
root.title("CH Monster Health Calculator")
root.geometry("400x300")

input_label = tk.Label(text="あああああ！")
input_label.place(x=10 , y=80)

label = tk.Label(text="Level:")
label.place(x=10 , y=100)

input_box = tk.Entry(width=10)
input_box.place(x=50 , y=100)

from tkinter import messagebox

def button_click():
  input_value = input_box.get()
  messagebox.showinfo("Result" , CH_MonsterHealth(input_value) + "！！！！")


button = tk.Button(text="FIGHT" , command=button_click)
button.place(x=10 , y=140)

button2 = tk.Button(text=" ACT ")
button2.place(x=60 , y=140)

button3 = tk.Button(text="ITEM ")
button3.place(x=110 , y=140)

button4 = tk.Button(text="MERCY" , command=root.destroy)
button4.place(x=160 , y=140)

from tkinter import font

la5 = tk.Label(root,
               text="a",
               font=("",25))
la5.place(x=350 , y=250)


la4 = tk.Label(root,
               text="a",
               font=("",20))
la4.place(x=365 , y=230)

la3 = tk.Label(root,
               text="a",
               font=("",25))
la3.place(x=370 , y=200)

la2 = tk.Label(root,
               text="a",
               font=("",20))
la2.place(x=370 , y=175)

la1 = tk.Label(root,
               text="a",
               font=("",35))
la1.place(x=360 , y=130)

title = tk.Label(root,
                 text="I Have Too Much Space.",
                 font=("",8))
title.place(x=250 , y=210)

root.mainloop()
"""

"""# 3乗根"""

import random as r
import time

i = 1

print("3乗根を答えてね (1-100)")
print()

t1 = time.time()

while i <= 10:
  j = 1
  x = r.randint(1 , 100)
  while j <= 1:
    print(str(i) + "問目 : " + str(x ** 3))
    y = input("回答 : ")
    if y.isdigit() == True:
      y = int(y)
    else:
      print("ばーか")
      i = 2147483647
      break
    if x == y:
      print("正解")
      print()
      i = i + 1
    else:
      print("ちがう")
      print()
      continue
    j = j + 1

t2 = time.time()
elapsed_time = t2 - t1

if i != 2147483647:
  print("congrats")
  print("Time : " + str(round(elapsed_time , 2)) + "s")

"""#5乗根"""

import random as r
import time as t

print("5乗根 (1-100)")
print()

i = 1

t1 = t.time()

while i <= 10:
  x = r.randint(1,100)
  j = 1
  while j <= 1:
    print(str(i) + "問目 " + str(x ** 5))
    y = input("回答 : ")
    #print(x)
    if y.isdigit() == False:
      print("ばーか")
      print()
      continue
    else:
      y = int(y)
      if x == y:
        print("正解")
        print()
      else:
        print("ちがう")
        print()
        continue
      j = j+1
  i = i+1

t2 = t.time()
elapsed_time = t2-t1

print("congrats")
print("Time : " + str(round(elapsed_time , 2)) + "s")

"""#PARTY PARROT"""

x = input("えんたー ぷりーず : ")
x = x[1:]
print(x)

y = input("えんたー ぷりーず : ")
y = y[4]+y[1]+y[3]
print(y)

letter = input("えんたーーーー いやーー : ") 
letlist = []

for lets in letter:
  letlist.append(lets)
#print(letlist)

i = 1
while i <= len(letlist)-1:
  if letlist[i-1]+letlist[i] == "ちん":
    letlist[i] = "んちん"
  elif letlist[i-1]+letlist[i] == "チン":
    letlist[i] = "ンチン"
  i = i+1
#print(letlist)

結果 = ""
for x in letlist:
  結果 = 結果 + x
print(結果)

"""# LW"""

text = """1 1
2 7
3 19
4 37
5 61
6 91
7 127
8 169
9 217
10 271
11 331
12 397
13 469
14 547
15 631
16 721
17 817
18 919
19 1027
20 1141
21 1261
22 1387
23 1519
24 1657
25 1801
26 1951
27 2107
28 2269
29 2437
30 2611
31 2791
32 2977
33 3169
34 3367
35 3571
36 3781
37 3997
38 4219
39 4447
40 4681
41 4921
42 5167
43 5419
44 5677
45 5991
46 6211
47 6487
48 6769
49 7057
50 7351
51 7651
52 7957
53 8269
54 8587
55 8911
56 9241
57 9577
58 9919
59 10267
60 10621
61 10981
62 11347
63 11719
64 12097
65 12481
66 12871
67 13267
68 13669
69 14077
70 14491
71 14911
72 15337
73 15769
74 16207
75 16651
76 17101
77 17557
78 18019
79 18487
80 18961
81 19441
82 19927
83 20419
84 20917
85 21421
86 21931
87 22447
88 22969
89 23497
90 24000
91 25200
92 26400
93 28800
94 31200
95 36000
96 42000
97 48000
98 72000
99 158400
100 MAX"""

print(text)

"""# π"""

print("円周率πの近似")
nth = input("Till When:")
print()

n = 0
和 = 0

if nth.isdecimal() == True:
  nth = int(nth)
  while n < nth:
    formula = (-1)**n / (2*n+1)
    和 = 和 + formula
    n = n+1
    print(str(n) + ":" + str(4*和))
else:
  print("ばーか")

"""# How Crazy RNG It Was Calculator"""

import math as m

print("m回中n回x%を引き当てた時の確率を計算します。")
print()

def test():
  print("Success")
def a():
  print("ばーか")
def gnn():
  print("ぐぬぬ")
def tryfloat(x):
  try:
    float(x)
  except ValueError:
    return False
  else:
    return True



tries = input("m:試行回数を入力してください : ")
if tries.isdecimal() == True:
  tries = int(tries)
  if tries > 0:
    wins = input("n:当たりの回数を入力してください : ")
    if wins.isdecimal() == True:
      wins = int(wins)
      if wins >= 0:
        if wins <= tries:
          odds = input("x:当たりの確率を入力してください[%] : ")
          if tryfloat(odds) == True:
            odds = float(odds)
            if odds > 0:
              odds = odds / 100
              answer = m.factorial(tries) / m.factorial(tries - wins) / m.factorial(wins) * (odds ** wins) * ((1 - odds) ** (tries - wins))
              print(str(round(answer * 100 , 3)) + "%です")
            else:
              a()
          else:
            a()
        else:
          gnn()
      else:
        a()
    else:
      a()
  else:
    a()
else:
  a()

"""# How Many  Rectangles In This Grid Calculator"""

print("A×Bの方眼の中に何個の四角形があるか計算します。")
print()

def a():
  print("ばーか")



A = input("1つの辺の長さを入力してください : ")
if A.isdecimal() == True:
  A = int(A)
  B = input("もう1つの辺の長さを入力してください : ")
  if B.isdecimal() == True:
    B = int(B)
    answer = A * (A+1) * B * (B+1) / 4
    print("四角形は" + str(int(answer)) + "個")
  else:
    a()
else:
  a()